{
    "name": "IP FarmBook",
    "version": "17.0.1.0.0",
    "category": "Agriculture",
    "summary": "Operasional budidaya, panen, stok, dashboard, dan rekap IP FarmBook",
    "author": "IF3141 K02 G03",
    "license": "LGPL-3",
    "depends": ["base", "hr", "uom"],
    "data": [
        "security/ipfarm_security.xml",
        "security/ir.model.access.csv",
        "data/ipfarm_sequence.xml",
        "report/ipfarm_report_templates.xml",
        "report/ipfarm_report_actions.xml",
        "views/ipfarm_bibit_views.xml",
        "views/ipfarm_ruangan_views.xml",
        "views/ipfarm_penanaman_views.xml",
        "views/ipfarm_batch_views.xml",
        "views/ipfarm_estimasi_panen_history_views.xml",
        "views/ipfarm_produk_views.xml",
        "views/ipfarm_panen_views.xml",
        "views/ipfarm_pemrosesan_views.xml",
        "views/ipfarm_histori_stok_views.xml",
        "views/ipfarm_dashboard_views.xml",
        "views/ipfarm_report_wizard_views.xml",
        "views/ipfarm_menu.xml",
    ],
    "application": True,
    "installable": True,
}
